### ISSUE TITLE
first number of format is wrong with prefix

### ISSUE THREAD

**Issue by Lukaalimbarashvili** [RedMadRobot/input-mask-ios#109]
static let main = +998  + " " + "[00] [000] [00] [00]"

phoneFormatter.format(with: main, phone: “998909933344”) // output :  "+998 90 933 33 44" correct
phoneFormatter.format(with: main, phone: “909933344”) // output: "+998 09 333 34 4" wrong
phoneFormatter.format(with: main, phone: “509933344”) // output: "+998 50 933 33 44" correct

If mast prefix starts with +998 it has problem with numbers starting with 9 or 8, for example if mask prefix contains +112 it has problem with numbers starting 1 or 2

**Comment by Lukaalimbarashvili** [comment]
func format(with mask: String, input: String) -> String {
        let mask: Mask = try! Mask(format: mask)
        let result: Mask.Result = mask.apply (
            toText: CaretString(string: input, caretPosition: input.endIndex, caretGravity: .forward)
        )
        let output: String = result.formattedText.string
        return output
    }

**Comment by Lukaalimbarashvili** [comment]
`   func format(with mask: String, input: String) -> String {
        let mask: Mask = try! Mask(format: mask)
        let result: Mask.Result = mask.apply (
            toText: CaretString(string: input, caretPosition: input.endIndex, caretGravity: .forward)
        )
        let output: String = result.formattedText.string
        return output
    }`

**Comment by Lukaalimbarashvili** [comment]
`   func format(with mask: String, input: String) -> String {
        let mask: Mask = try! Mask(format: mask)
        let result: Mask.Result = mask.apply (
            toText: CaretString(string: input, caretPosition: input.endIndex, caretGravity: .forward)
        )
        let output: String = result.formattedText.string
        return output
    }`

**Comment by taflanidi** [comment]
Please look through the existing issues.

https://github.com/RedMadRobot/input-mask-ios/issues/104
