### ISSUE TITLE
Masked text to a Plan text

### ISSUE THREAD

**Issue by cubixlabs** [RedMadRobot/input-mask-ios#11]
I am able to do masking but now after successful masking I want to do it reverse mask so that I may send plan text to server. for example if a user enters: (56)-55 (for mask formate ([11])-[11]), I want to make it plan text like 5665 and use it.

Please note that extractedValue is not returning plan text (unmasked text) if it is an issue then, it should be resolved as already referenced [here](https://github.com/RedMadRobot/input-mask-ios/issues/9)

**Comment by taflanidi** [comment]
Hi @cubixlabs!
I'm not sure I got you right. 
First of all, `([11])-[11]` format is not correct. 

If you would like to achieve a formatted text like `(56)-55`, and collect extracted value from it containing only digits (like `5655`) — you should use the `([00])-[00]` format.

There's a [bunch of test cases](https://github.com/RedMadRobot/input-mask-ios/blob/master/Source/InputMask/InputMaskTests/Classes/Mask/PhoneCase.swift) for phone numbers in our library; those demonstrate how to extract a "plain text" out of the user input.

For instance, in [this test case](https://github.com/RedMadRobot/input-mask-ios/blob/master/Source/InputMask/InputMaskTests/Classes/Mask/PhoneCase.swift#L444) there's a mask format `+7 ([000]) [000] [00] [00]` and an [input string](https://github.com/RedMadRobot/input-mask-ios/blob/master/Source/InputMask/InputMaskTests/Classes/Mask/PhoneCase.swift#L445) like `+7 (123) 456 78 90`. The [expected value](https://github.com/RedMadRobot/input-mask-ios/blob/master/Source/InputMask/InputMaskTests/Classes/Mask/PhoneCase.swift#L450) is `1234567890`, which pretty much corresponds to "an extracted plain text".

Please provide some additional details on your implementation; extracting a "plain text" is a quite basic functionality and I'm definitely sure it is working properly.
