### ISSUE TITLE
Being able to use the `UITextField` delegates

### ISSUE THREAD

**Issue by muradtries** [RedMadRobot/input-mask-ios#110]
After upgrading to version `7.0.0`, it seems like `MaskedTextInputListener` no more inherits from `UITextFieldDelegate`. Is there any workaround for having an access to those delegate methods while also applying the input mask?

**Comment by muradtries** [comment]
Hey @taflanidi 
Sorry for not following the template. I'll apply it on my next issues, in case.

After looking at the sources I had to clarify that, I made mistake with my question. The thing I need that being able to having access to `UITextField` delegate methods such as `MaskedTextFieldDelegateListener` had with new delegate method `OnMaskedTextChangedListener`. 

The previous one was inheriting from `UITextFieldDelegate` which was providing me with editing begin and ends. However new one has no such ability since it's inheriting directly from `NSObject`.

**Comment by muradtries** [comment]
Yes, as previous one it'd be good having an access to `UITextFieldDelegate` calls to with `listener`. Because on our end we can assign one delegate to our `UITextField`. Thanks for your quick support and guidance.

**Comment by taflanidi** [comment]
Okay, meet `7.2.8`.

Let me know if it works for you (-:

**Comment by taflanidi** [comment]
Hey @muradtries 

First, could you please implement the `textFieldDidEndEditing(_, reason:)` as well and clarify whether it's called or not?

Second thought, the `textFieldDidEndEditing` is called when the field resigns first responder, so the question is when do you expect it to fire and what happens at that moment?

**Comment by muradtries** [comment]
Interestingly, `textFieldDidEndEditing(_, reason:)` gets called with the rawValue of 0. For the second question - my textfield should get resigned when I tap the space above the keyboard or clicking `return` button on keyboard.

**Comment by taflanidi** [comment]
@muradtries okay it might have something to do with backward compatibility since the method was introduced later.  
See [here](https://stackoverflow.com/a/62427696/3756295).

I do believe it might be a good idea to have both delegate methods implemented, does it work for you?

And it seems immagonna add yet an another known issue after investigation…

**Comment by taflanidi** [comment]
@muradtries greets

Got any news?

**Comment by muradtries** [comment]
Hii @taflanidi 

I'm so sorry that I forgot to turn back to thread. As we discussed only the delegate method with reason one, got called. So I continued with that. I still didn't understand why the another method wasn't called. 

Btw, I think that the main problem of this issue resolved by new release. Maybe you can close it by now.
