### ISSUE TITLE
Обрыв событийной модели при изменении текста

### ISSUE THREAD

**Issue by dst-bengus** [RedMadRobot/input-mask-ios#12]
Добрый день. Во первых хочется сказать спасибо за отличную библиотеку.

Столкнулся с тем, что MaskedTextFieldDelegate в методе

```
open func textField(
        _ textField: UITextField,
        shouldChangeCharactersIn range: NSRange,
        replacementString string: String) -> Bool {
        
        let extractedValue: String
        let complete:       Bool
        
        if isDeletion(
            inRange: range,
            string: string
        ) {
            (extractedValue, complete) = self.deleteText(inRange: range, inField: textField)
        } else {
            (extractedValue, complete) = self.modifyText(inRange: range, inField: textField, withText: string)
        }
        
        self.listener?.textField?(
            textField,
            didFillMandatoryCharacters: complete,
            didExtractValue: extractedValue
        )
        let _ = self.listener?.textField?(textField, shouldChangeCharactersIn: range, replacementString: string)        
        return false
    }
```

всегда возвращает false, что не дает сработать событиям ни через NotificationCenter ни через actions for controlEvents. хотя в этом методе так или иначе изменится свойство text у textField.

Возможно решение не самое лучшее, но как временную заплатку у себя поправил, добавив перед возвратом вызов поста события в NotificationCenter и вызов actions для события editingChanged 

```
open func textField(
        _ textField: UITextField,
        shouldChangeCharactersIn range: NSRange,
        replacementString string: String) -> Bool {
        
        let extractedValue: String
        let complete:       Bool
        
        if isDeletion(
            inRange: range,
            string: string
        ) {
            (extractedValue, complete) = self.deleteText(inRange: range, inField: textField)
        } else {
            (extractedValue, complete) = self.modifyText(inRange: range, inField: textField, withText: string)
        }
        
        self.listener?.textField?(
            textField,
            didFillMandatoryCharacters: complete,
            didExtractValue: extractedValue
        )
        let _ = self.listener?.textField?(textField, shouldChangeCharactersIn: range, replacementString: string)
        
        NotificationCenter.default.post(name: .UITextFieldTextDidChange, object: textField)
        textField.sendActions(for: .editingChanged)
        
        return false
    }
```

Что думаете на этот счет?

**Comment by taflanidi** [comment]
@dst-bengus, привет.
Спасибо за отзыв.

Замечание по делу, спору нет. Но `false` там возвращается намеренно, и отсутствие событий — это design flaw от Apple.

Касательно предложенного решения. Такая заплатка нарушает [OCP](https://en.wikipedia.org/wiki/Open/closed_principle), а я бы настоятельно рекомендовал придерживаться ООП-парадигмы.

Например, следуя [LSP](https://en.wikipedia.org/wiki/Liskov_substitution_principle):

```swift
class NotifyingMaskedTextFieldDelegate: MaskedTextFieldDelegate {
    override func textField(
        _ textField: UITextField,
        shouldChangeCharactersIn range: NSRange,
        replacementString string: String
    ) -> Bool {
        defer {
            NotificationCenter.default.post(name: .UITextFieldTextDidChange, object: textField)
            textField.sendActions(for: .editingChanged)
        }
        return super.textField(textField, shouldChangeCharactersIn: range, replacementString: string)
    }
}
```

От себя.
Развивая мысль про отсутствие уведомлений от `NotificationCenter` и событий `editingChanged`, мой совет: не использовать эти механизмы без необходимости.

_Явный_ вызов _явного_ метода _явного_ слушателя когда-нибудь скрасит отладку Вам или Вашим коллегам. 

```swift
class NotifyingMaskedTextFieldDelegate: MaskedTextFieldDelegate {
    weak var editingListener: NotifyingMaskedTextFieldDelegateListener?
    
    override func textField(
        _ textField: UITextField,
        shouldChangeCharactersIn range: NSRange,
        replacementString string: String
    ) -> Bool {
        defer {
            self.editingListener?.onEditingChanged(inTextField: textField)
        }
        return super.textField(textField, shouldChangeCharactersIn: range, replacementString: string)
    }
}


protocol NotifyingMaskedTextFieldDelegateListener: class {
    func onEditingChanged(inTextField: UITextField)
}
```

Шины и очереди событий, в конце-концов, были придуманы совсем для других целей.

**Comment by dst-bengus** [comment]
@taflanidi Спасибо за такой быстрый ответ.
 Да так будет сильно лучше с NotifyingMaskedTextFieldDelegate. Про отсутствие событий понимаю. Просто мне очень нравится, что Ваша библиотека не вмешивается в сам UITextField и максимально сделана снаружи. завтра убрали и +/- все работает. Просто textField без Вашего делегата, при изменении контента пользователем так или иначе явится емиттером выше перечисленные мной "событий". А у Вы возвращаете false, чтобы на себя взять преобразования и затем положить преобразованный контент в свойство text. Получается свойство text изменилось в следствии действий пользователя, а оповещения не случились. В таком случае Вы меняете ожидаемое поведение системного контрола. считаю, что это неочевидно и плохо.

Стараюсь не использовать глобальные нотификации и предпочитаю делегирование и обзервинг снаружи как раз по причине вашей рекомендации "Явный вызов явного метода явного слушателя когда-нибудь скрасит отладку Вам или Вашим коллегам."))

Если бы изменения требовалось трекать снаружи textField на уровне контроллера или супервью так, как вы предлагаете и сделал бы, но вынужден из наследника FloatingLabelUITextField: UITextField понимать, что контент в нем самом изменился и поэтому в init... подписываюсь add target forControlEvents: .editingChanged... а в deinit отписываюсь. В этом сабклассе UITextField переопределен drawRect и при изменении если текст не пуст изменяется editingRect смещаю рект ввода ниже а над текстом рисуется маленький title, а когда текст отсутствует rect возвращается на место и отображается обычный плейсхолдер. Не знаю способа лучше из самого textField узнать об изменениях в нем кроме как NotificationCenter или targets forControlEvents... 

Может быть вы порекомендуете что-то лучше?

**Comment by dst-bengus** [comment]
@taflanidi, Вы были правы. Вопрос отпал сам собой. Сделал все снаружи. Поле для ввода - есть поле для ввода. И не гоже городить туда еще что-то. Обернул снаружи во FloatLabeledWrapper, а его снаружи в ValidationWrapper. управляется тоже все снаружи. и друг от друга не зависит. А Controller или Layout сами слушают UITextView/UITextField и переводят в нужный state FloatLabeledWrapper и просят показать или убрать сообщение валидации ValidationWrapper. Спасибо за Ваши рекомендации. Вероятно стоит закрыть issue?

**Comment by taflanidi** [comment]
@dst-bengus, доброго времени суток. Не торопитесь закрывать issue. Проблема решена, но этого недостаточно.
Мне понадобилось время, чтобы разложить всё по полочкам, и ниже я привожу результат этих рассуждений.

Итак, суть в том, что **в текстовом поле меняется текст, но оповещение об этом не приходит**.

С одной стороны, имитировать уведомления от `UITextField` — это явный костыль и слишком большая ответственность для библиотеки InputMask.
Брать на себя функции iOS SDK здесь будет очень инвазивной процедурой, ибо таким образом мы «копируем» поведение текстового поля, берём толику его функций на себя. 

С другой стороны, [документация](https://developer.apple.com/documentation/uikit/uitextfielddelegate/1619599-textfield#discussion) к методу 
`textField(_:shouldChangeCharactersIn:replacementString:)`
чётко постулирует:

> Use this method to validate text as it is typed by the user.

— причём метод возвращает `Bool`. 
Он не возвращает строку, которую можно было бы скорректировать перед вставкой в поле, он возвращает вердикт `позволить редактировать` или `не позволить редактировать`.

iOS SDK не ожидает, что во время выполнения этого метода в текст будут вноситься какие-то правки, и здесь библиотека InputMask, на первый взгляд, нарушает правила.

Но это не так, и вот почему.

Уведомления `UITextFieldTextDidChange` и `editingChanged` касаются изменения свойства `textField.text`. Если текст меняется — должно быть отправлено уведомление.

Вы очень точно подметили, что библиотека не вмешивается в `UITextField`, не патчит его поведение и не переопределяет класс под себя. Это было одной из целей при написании исходного кода, ибо разнообразных текстовых полей (библиотек) со своими «плюшками» пруд пруди, и хотелось бы иметь возможность комбинировать поведение. Это касается как iOS, так и Android-платформы. И там, и там есть свои `MaterialEditText` и `FloatingLabelTextField`.

Именно поэтому InputMask не лезет в «кишки» текстового поля, а модифицирует текст [явно](https://github.com/RedMadRobot/input-mask-ios/blob/master/Source/InputMask/InputMask/Classes/View/MaskedTextFieldDelegate.swift#L233):
```swift
field.text = result.formattedText.string
```
И на этом месте я хотел бы обратить Ваше внимание на [исходный код](https://github.com/RedMadRobot/input-mask-android/blob/master/inputmask/src/main/kotlin/com/redmadrobot/inputmask/MaskedTextChangedListener.kt#L110) нашей же библиотеки, но под Android:
```kotlin
this.field.get()?.removeTextChangedListener(this)
edit?.replace(0, edit.length, this.afterText)
this.field.get()?.setSelection(this.caretPosition)
this.field.get()?.addTextChangedListener(this)
```
Здесь происходит следующее:
1. Библиотека **отписывается** от уведомлений об изменении текста;
2. Библиотека меняет текст;
3. Библиотека устанавливает курсор в новое положение;
4. Библиотека обратно **подписывается** на уведомления об изменении текста.

Думаю, Вы уже поняли, что это происходит во избежание зацикливания. Библиотека скорректировала текст, значит, должно прийти уведомление об этом.

Это является очевидным и корректным поведением текстового поля.
И именно поэтому я считаю отсутствие уведомлений от `UITextField` плохим дизайном.

**Однако**, проблема от этого вывода сама не решится, и пользователям InputMask от этого вывода легче не станет. Поэтому я предлагаю по аналогии с [Android-версией](https://github.com/RedMadRobot/input-mask-android#known-issues) завести в README для версии под iOS раздел «**Known Issues**», и первый пункт в нём будет посвящён этой проблеме и её решению в виде `NotifyingMaskedTextFieldDelegate`.

Что думаете по этому поводу? Сделаете pull request?

**Comment by taflanidi** [comment]
UPD: опустил target до iOS 8.0

**Comment by dst-bengus** [comment]
@taflanidi, Доброго времени суток. Pull request сделал. По поводу target 8.0 спасибо, но мне кажется есть небольшая проблема. в Podfile 8.0, но в самом проекте фреймворка и прожекте и в таргете Deployment target осталась 9.0. Вероятно машинально это не было замечено?

**Comment by taflanidi** [comment]
@dst-bengus, pull request принял, спасибо.

> но в самом проекте фреймворка и прожекте и в таргете Deployment target осталась 9.0

Точно. Глянул сейчас [правки](https://github.com/RedMadRobot/input-mask-ios/commit/79a9ca848f070817e856cd207724ab255382e224) — для Sample-проекта target поставил правильный, а про проект фреймворка забыл.

Поправлю сегодня, [задачу](https://github.com/RedMadRobot/input-mask-ios/issues/17) завёл.
Вот теперь, наверное, этот issue можно закрывать.

**Comment by dst-bengus** [comment]
@taflanidi Спасибо.
