### ISSUE TITLE
Deployment target

### ISSUE THREAD

**Issue by vani2** [RedMadRobot/input-mask-ios#2]
Hi! Is't possible to low min iOS target version to 8.0 or 9.0?

**Comment by taflanidi** [comment]
Min iOS target version lowered to 9.0.

**Comment by paulofaria** [comment]
Is it possible to lower it to 8.0?

**Comment by taflanidi** [comment]
Hey @paulofaria!
I'm pretty much sure the target version could be lowered to iOS 8.0 or even 7.0, but I still need to look into it a little. I'll be able to give you an answer (w/ corresponding lib update, if any) in a day or two.

Meanwhile, you may open a separate feature request for maintenance reasons
