### ISSUE TITLE
Mask Brazilian's CPF and CNPJ in the same field

### ISSUE THREAD

**Issue by grsouza** [RedMadRobot/input-mask-ios#26]
Hi, in Brazil we have there registration numbers named CPF and CNPJ.

The formats are:
- CPF:   [000].[000].[000]-[00]
- CNPJ: [00].[000].[000]/[0000]-[00]

I wasn't able to figure it out a way of doing this, maybe changing the masked delegate at runtime? How can I do it?

Thanks.

**Comment by taflanidi** [comment]
Hi @grsouza!
Thanks for your question.

I had somewhat a similar conversation regarding Brazilian phone numbers here:
https://github.com/RedMadRobot/input-mask-ios/issues/8
— might it be of help?

**Comment by taflanidi** [comment]
Closing as outdated.
