### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dhyogoalmeida** [RedMadRobot/input-mask-ios#27]
Are you still maintaining this framework?

**Comment by taflanidi** [comment]
Hey @dhyogoalmeida,
Yes, and we are going to issue an update with Swift 4 and some other features this week.

Thanks for your patience (-:

**Comment by dhyogoalmeida** [comment]
@taflanidi ,
I really liked your framework and plan to use it in my project.

Thank you for your feedback.

**Comment by taflanidi** [comment]
@dhyogoalmeida, please welcome Swift 4.1 update.

**Comment by dhyogoalmeida** [comment]
@taflanidi , great!!!
