### ISSUE TITLE
Dependency "input-mask-ios" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by osterlind** [RedMadRobot/input-mask-ios#29]
With the latest update of 3.0.0 we can not build our input-mask-ios Carthage dependency. The Xcode project is removed from the dist.

Carthage 0.29.0
Xcode 9.3

**Comment by taflanidi** [comment]
@osterlind,
Thanks for your report.

Oh my, somehow I was sure Carthage had adopted *.xcproj-less builds, like the SPM.
I'll return it back a little bit later today, so stay tuned.

**Comment by taflanidi** [comment]
@osterlind,
Alright, I've rolled out a patch. Everything should be back to normal now.

**Comment by osterlind** [comment]
Perfect! Now 3.0.1 work just fine with Carthage. 
Thanks!
