### ISSUE TITLE
No outlets 

### ISSUE THREAD

**Issue by kiokumicu** [RedMadRobot/input-mask-ios#30]
On storyboard, can't set delegate outlet from listener to view controller.
No outlets section in submenu.
![2018-04-10 11 02 57](https://user-images.githubusercontent.com/26886/38543883-82bf7654-3cae-11e8-91f3-46edec9666e6.png)

**Comment by taflanidi** [comment]
Hi @kiokumicu!
Thanks for your report.

Could you, please, be more specific? `MaskedTextFieldDelegateListener` is a protocol, it doesn't contain any outlets and it wasn't supposed to.

**Comment by kiokumicu** [comment]
I install lib via Carthage.
Trying to follow instruction in Usage section, where use storyboard.
On screenshot ![Screenshot](https://raw.githubusercontent.com/RedMadRobot/input-mask-ios/assets/Assets/shot.png) you have outlet delegate to VC.

**Comment by taflanidi** [comment]
@kiokumicu,
Thanks for the details.

You should know there's an old issue with IBDesignables and IBInspectables in dynamic frameworks.
Guys from Carthage have a couple of workarounds described in the [corresponding discussion](https://github.com/Carthage/Carthage/issues/335). 

You may also consider filing a radar similar to [this](https://openradar.appspot.com/23114017). Duplicate radars increase issue priority, but it seems there's not a lot of motion regarding this defect.

**Comment by kiokumicu** [comment]
OK, I try it later.
Thx.
