### ISSUE TITLE
Unable to compile in Xcode 9.3 / Swift 4

### ISSUE THREAD

**Issue by byjoh** [RedMadRobot/input-mask-ios#34]
unless I change initialState in Mask.swift and customNotations in Compiler.swift to fileprivate (from private)

**Comment by taflanidi** [comment]
Hi @byjoh!
Thanks for your report.

I need slightly more details from you about your project.
How do you use our library, is it a pod or a Carthage dependency? Could you share your failing project or simplified/obfuscated version of it?

Also, have you been able to run our [Sample](https://github.com/RedMadRobot/input-mask-ios/tree/master/Source/Sample)?

As you may probably have guessed, it seems like compiler uses old version of Swift, where `private` access modifier restricts and divides scope between extensions.

**Comment by byjoh** [comment]
I am using a pod (v3.4).  Unfortunately it would be impossible for me to share the project.  Is there any other information I can give you that would be helpful?  Yes, I was able to successfully run the sample (using pods).

**Comment by taflanidi** [comment]
@byjoh,
Just to make sure we are on the same page, did you check POD build settings in your project? I'm interested in this particular setting:

<img width="1158" alt="screen shot 2018-05-10 at 19 00 08" src="https://user-images.githubusercontent.com/6849363/39879984-0c632c6e-5485-11e8-8f11-9ca08e480368.png">

— for both `InputMask` and `Pods-YourProject`.

**Comment by byjoh** [comment]
sorry for the delay, yes that was it.  thanks!
