### ISSUE TITLE
Error while using profiler

### ISSUE THREAD

**Issue by KompoD** [RedMadRobot/input-mask-ios#35]
Hey guys!
I recently tested my app and while try to profile memory leaks I got error in `FormatSanitizer.swift` in ` func getFormatBlocks(_ string: String) -> [String]` block.
![2018-05-11 12 43 17](https://user-images.githubusercontent.com/14116289/39918663-dfe38b4e-5519-11e8-8623-5153fef3f910.png)

Error message is `Main Thread Checker: UI API called on a background thread: -[UIView retainCount]
PID: 1884, TID: 190199, Thread name: (none), Queue name: com.apple.keyboard.xpc, QoS: 25`
Please check this :)

P.S. Thanks for awesome library! 👍🏻

**Comment by taflanidi** [comment]
Hey @KompoD!
Thanks for your report.

I'll try to reproduce your issue. Meanwhile, how often do you get this error?

**Comment by KompoD** [comment]
@taflanidi I just started typing first symbol in masked textfield and catch this error.

**Comment by taflanidi** [comment]
@KompoD,
Alright, I've reproduced your issue, and it seems I've found a potential solution.

Could you try profiling your project with a "Blank" profiler template by adding necessary instruments? See below.

1.
<img width="804" alt="screen shot 2018-05-11 at 21 54 53" src="https://user-images.githubusercontent.com/6849363/39941812-68fdead6-5566-11e8-9df6-25d48b45b70e.png">

2.
<img width="1445" alt="screen shot 2018-05-11 at 21 55 11" src="https://user-images.githubusercontent.com/6849363/39941820-70745232-5566-11e8-9e2b-c395619aea44.png">

3.
<img width="1445" alt="screen shot 2018-05-11 at 21 55 26" src="https://user-images.githubusercontent.com/6849363/39941830-76c12e9e-5566-11e8-8bca-1289cc6a22b0.png">

Please, share your results.

**Comment by KompoD** [comment]
@taflanidi, using Blank I have no errors. It's magic :)
P.S. Sorry for late answer.

**Comment by taflanidi** [comment]
@KompoD you're welcome.
