### ISSUE TITLE
Whitespace symbols as required

### ISSUE THREAD

**Issue by kravtsovguy** [RedMadRobot/input-mask-ios#37]
I figured out that if I have this mask "[0] [9]" than there is a issue
Type to textfield "1 2" - OK
Type to textfield "1" - OK
Type to textfield "1 " - Not OK

Whitespace characters are treated as required symbols, it shouldn't be like this because it isn't obvious
It should be OK for string "1 "

**Comment by kravtsovguy** [comment]
see pull request [#38](https://github.com/RedMadRobot/input-mask-ios/pull/38)

**Comment by taflanidi** [comment]
Hello @kravtsovguy, thanks for your report.
In short, I won't accept a made up hardcode like this.

> Whitespace characters are treated as required symbols, it shouldn't be like this because it isn't obvious

You are making a notably big statement for a guy who doesn't consider clarifying internal library design policies first before publishing pull requests altering core behaviour. 

Your issue report lacks arguments and real life examples. What does your `[0] [9]` mask format stand for? And why whitespaces only?
