### ISSUE TITLE
Appending text.

### ISSUE THREAD

**Issue by erneestoc** [RedMadRobot/input-mask-ios#39]
I have a case where I'm trying to ender a numeric value, and appending a string at the end.. Can't get to get it working, and the documentation is not obvious..

Example:
Input `1` should look like `1 pts`, and `2000` as `2000 pts`..

I tried doing something like `[0…]{ pts}`, and multiple other combinations. What would be the way to format this text?

**Comment by erneestoc** [comment]
Just realized there is a `ReversedMaskTextFieldDelegate`, which I think is not well documented. Only problem I see is the mask is only being applied when deleting characters, not when inputing something. Why is this, or how can I achieve the behavior I'm expecting?

**Comment by taflanidi** [comment]
Hey @erneestoc, sorry for the delay.
Have you solved your issue?
