### ISSUE TITLE
TextView support

### ISSUE THREAD

**Issue by AlexisQapa** [RedMadRobot/input-mask-ios#40]
Hi, 

I've been using your lib in my app but I have to convert a textfield to a textview for growing text support. Is there a quick way to make it works with textview or should I port the code.

**Comment by taflanidi** [comment]
Hey @AlexisQapa, thanks for your question.

I'm on a short vacation right now, unfortunately.
I'll be able to add `UITextView` support early next week. I suppose this new module to be quite similar to the current `UITextFieldDelegate` implementation in our library, so it shouldn't take long.

Stay tuned for upcoming updates!

**Comment by AlexisQapa** [comment]
I've been playing a bit with it and I got it working. It's mostly changing methods signatures except for two things that will need discussion : 

- there is no clear button so : textViewShouldClear(_ textView: UITextView) -> Bool is useless. Maybe you could keep it somehow  so if one add a clear button he can get the same behaviour.

- the done button input a newline instead of delegating keyboard dismissal. You could add a toggle with something like : 
`
open func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String) -> Bool {
        // Hack to detect enter key
        if toggle {
            let resultRange = text.rangeOfCharacter(from: .newlines, options: .backwards)
            if text.count == 1 && resultRange?.lowerBound != nil {
                textView.resignFirstResponder()
                return false
            }
        }
...
`
 in order to have the same behaviour as for the TextField but keep it optin as it's mostly a hack and ppl may want to input newLines.

Finally, you may want to have only one delegate class, so maybe a wrapper or the listener could implement UITextFieldDelegate and UITextViewDelegate

**Comment by taflanidi** [comment]
Implemented in `3.5.0`.
