### ISSUE TITLE
3.4.1 cannot be use with ObjC

### ISSUE THREAD

**Issue by suthee-p** [RedMadRobot/input-mask-ios#43]
Cannot access MaskedTextFieldDelegate.listener from ObjC because it declares as
**open weak var listener: MaskedTextFieldDelegateListener?**

Question: Is there any other option to use it without edit the code and add **@objc** ?

**Comment by taflanidi** [comment]
Hi @suthee-p!
Haven't you tried the `MaskedTextFieldDelegate.delegate` property? 
It's an «`NSObject`» backed by the `MaskedTextFieldDelegate.listener` field.

**Comment by suthee-p** [comment]
@taflanidi, cool! I must have used the listener property for a long time and didn't notice that it has a delegate property too. Thank you for your time on this!
