### ISSUE TITLE
Symbol acceptance

### ISSUE THREAD

**Issue by Robuske** [RedMadRobot/input-mask-ios#46]
According to the documentation `_` and `-` accept any digits or letters, I understood that it would not add anything else, like punctuation, spaces, etc...
And it seems to not be adding it, but still counting as a symbol or something like that.

Using the mask
`"[---] [---] [---]"` (it is for passports, basically can have anything)
Wields strange results, if I only use numbers and letters everything goes ok, if I use space or any punctuation symbol it adds a space and jumps to the next brackets group.

I tried with
`"[---]-[---]-[---]"`
And it adds the `-`, that's why I think that it goes to the next group.

P.S.: Not related, but you did not update the documentation to reflect the removal of `PolyMaskTextFieldDelegate`

**Comment by Robuske** [comment]
`"[---------]"`
Seems to work fine, so the problem is with the separators

**Comment by taflanidi** [comment]
Hi @Robuske!
Thanks for your question.

It seems that you haven't tried `[___] [___] [___]` for some reason. Please, do so and come back with your results.

> P.S.: Not related, but you did not update the documentation to reflect the removal of `PolyMaskTextFieldDelegate`

Yeah, my bad, I need to compose a changelog after all. Still, the new version is `4.0.0`, and major version updates are expected to break API backward compatibility.

**Comment by Robuske** [comment]
Oh yes, I didn't realize it was a side effect of everything being optional, makes sense I guess.

> It seems that you haven't tried [___] [___] [___] for some reason.

Unfortunately, passports seem to have whatever the fuck format the country wants, so I can't retrict count. Although... I am not checking the "complete" property, so it could work.
Anyway `"[---------]"` looks ok, so I'll just go with it, thanks.

**Comment by taflanidi** [comment]
@Robuske for your information, there's also an elliptical mask `[-…]` in case you don't want to restrict text length.
