### ISSUE TITLE
Ignore autocompletion after deleting character.

### ISSUE THREAD

**Issue by ton252** [RedMadRobot/input-mask-ios#53]
For example: Input mask is "+ 7 ([000])-[000]-[00]-[00]".
Entered text: "+7 (999)-"

Now we press delete in keyboard.

Expected result: "+7 (99"
Current result: "+7 (999)"

I think we need to ignore ")-" symbols and delete the last "9" symbol.

**Comment by taflanidi** [comment]
Hey @ton252,
Thanks for your question!

Please, refer to the issue [#14](https://github.com/RedMadRobot/input-mask-android/issues/14) of the library's Android counterpart for the detailed explanation about why we are not going to support this behaviour you described in this library.

In the meantime, I've received your email, and by chance I've got a working solution for your case. I'll revert to your letter as soon as I can.

**Comment by ton252** [comment]
Thank's)
