### ISSUE TITLE
'DidEndEditingReason' is not a member type of 'UITextField'

### ISSUE THREAD

**Issue by daerimin** [RedMadRobot/input-mask-ios#56]
Thank you so much for this library - I'm using both Android and Swift versions, and I love it.  I did run into a little problem though on this version:

Line 167 of "MaskedTextFieldDelegate.swift":
'DidEndEditingReason' is not a member type of 'UITextField'

Assuming this is just a syntax change.  Could you update, or tell me what to do to resolve?

Thanks!!!

**Comment by taflanidi** [comment]
Hey @daerimin!
Thanks for your question.

We've migrated our codebase to Swift 4.2 recently. Could you please let me know if `InputMask` pod target is configured accordingly?

It might be that you need to update your own project language settings as well.

**Comment by daerimin** [comment]
Sorry for the late reply - this was absolutely correct.  I had been away from Xcode for a while, and didn't realize 4.2 had been released.  After updating, everything is good.

Thank you!!
