### ISSUE TITLE
Ability to set an empty mask

### ISSUE THREAD

**Issue by AlexisQapa** [RedMadRobot/input-mask-ios#59]
As I was making my inputs generics so all could take a mask I defaulted the mask to "" (the default in the lib code) and I all inputs stopped accepting chars. Think the empty mask should allow any char or the default should be an allow all mask.

**Comment by taflanidi** [comment]
Hey @AlexisQapa,
I'm afraid your suggestion is misleading.

Masks behave somewhat like regular expressions. Meaning that there should be an explicit "any character" in the mask format in order to accept any character.

Why won't you use `[…]` instead of empty string?

**Comment by AlexisQapa** [comment]
Yeah that's what I do. I just found strange that the default setting is not "[...]" then as by default UITextFields/UITextview accept anything by default.

**Comment by Banck** [comment]
@taflanidi Hello!
Why […] doesn't accept !@#$%^&* and other symbols?

**Comment by taflanidi** [comment]
Hi @Banck!
Because `…` defaults to `-`, which is a combination of digits and letters.

**Comment by Banck** [comment]
> Hi @Banck!
> Because `…` defaults to `-`, which is a combination of digits and letters.

But is there a mask which allow any characters?

**Comment by taflanidi** [comment]
@Banck, just use a text field without masking.
