### ISSUE TITLE
Is there a way to disable brackets

### ISSUE THREAD

**Issue by MrJox** [RedMadRobot/input-mask-ios#62]
As an input I have such mask: **+1(999)999 99 99**
This is equivalent to InputMask's **+1([000])[000] [00] [00]**
I setup a custom notation for this mask in the following way:

```
        let digitNotation = Notation(character: "9", characterSet: .decimalDigits, isOptional: false)
        let upperNotation = Notation(character: "A", characterSet: .uppercaseLetters, isOptional: false)
        let lowerNotation = Notation(character: "a", characterSet: .lowercaseLetters, isOptional: false)
        let alNumNotation = Notation(character: "*", characterSet: .alphanumerics, isOptional: false)
        let notations = [digitNotation, upperNotation, lowerNotation, alNumNotation]
        
        self.maskListener = MaskedTextFieldDelegate(primaryFormat: mask, customNotations: notations)
``` 

However since server doesn't send me brackets [], InputMask won't let me type my text properly according to the mask and would instead always output **+1(999)999 99 99** as is no matter what I type.

So the question: Is there a way I could tell InputMask engine not to use [] or at least replace brackets with nothing in similar passion as I did for notations?

**Comment by taflanidi** [comment]
Hey @MrJox!
Thanks for your question.

Our library needs to distinguish between the symbols for the end user to choose and the fixed ones. Square brackets mark groups of variable symbols; these symbols could be anything chosen by the user input; symbols in square brackets serve as placeholders. Everything outside square brackets is static and can't be altered. That's the main idea behind our library's engine.

For your particular case, I'd like to suggest you to simply adapt your server's masks replacing each `9` with `[0]`. It's a one-liner, and the result would look like this:

```
+1([0][0][0])[0][0][0] [0][0] [0][0]
```

While it's not really fancy, it should do the trick for you.
