### ISSUE TITLE
Adding optional symbol followed by mandatory letter not working 

### ISSUE THREAD

**Issue by luminkhant** [RedMadRobot/input-mask-ios#63]
I am current using inputMask to check my format with like that 
[-A]-[0000] but that mask is not working exactly for what I want.
Examples of my format - 
1A-1234
AA-1234
A-1234
But above mask ( [-A]-[0000] ) is not working for my last format ( A-1234 ). 
Help me with this please.  @taflanidi

**Comment by taflanidi** [comment]
Hey @luminkhant!
Thanks for your question. 

Please try adding an affine format to your listener as follows:
```swift
listener.affineFormats = [
    "[A]-[0000]"
]
```
— this will allow to manually put a dash after the first entered letter:
```
A
A-
A-1
```
Let me know if this solves your problem.

**Comment by taflanidi** [comment]
@luminkhant 

> But It wont solve my problem.

But why? You are not going to lose your primary format, it's going to work both ways.
```
[-A]-[0000]
[A]-[0000]
```

**Comment by luminkhant** [comment]
Thanks.. .
I got it.. 
I just have to use both Primary format and affine format array.
