### ISSUE TITLE
'customNotations' is inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by ppshein** [RedMadRobot/input-mask-ios#64]
`InputMask/Source/InputMask/InputMask/Classes/Helper/Compiler.swift:317:30: 'customNotations' is inaccessible due to 'private' protection level`

I've encountered above error message when I've upgraded my cocapods version to `1.5.3` as **swift 4.2**

**Comment by taflanidi** [comment]
Hey @ppshein! Thanks for your report.

It looks like the `Compiler` extension (`Compiler.swift:317`) doesn't have access to the private member property in the same file, which indicates outdated Swift version.

While I see that you've mentioned **Swift 4.2**, I've got to ask you to check the language version of both `InputMask` and `Pods` targets. Also, please let me know if this problem persists in out lib's sample project in your environment.

**Comment by ppshein** [comment]
> Hey @ppshein! Thanks for your report.
> 
> It looks like the `Compiler` extension (`Compiler.swift:317`) doesn't have access to the private member property in the same file, which indicates outdated Swift version.
> 
> While I see that you've mentioned **Swift 4.2**, I've got to ask you to check the language version of both `InputMask` and `Pods` targets. Also, please let me know if this problem persists in our lib's sample project in your environment.

Hi,

```
cocapods version = 1.5.3
swift = 4.2
InputMask = 4.0.0
```

**Comment by taflanidi** [comment]
Yep, you should.
