### ISSUE TITLE
Ability to define a mask with arbitrary number of groups

### ISSUE THREAD

**Issue by AlexisQapa** [RedMadRobot/input-mask-ios#66]
### Prerequisites
done.

### Summary
I'd like to define a mask that allows to input an arbitrary number of group of 4 letters separated by space.

### Motivation
Easy formatting for IBAN numbers for every country (different lengths)

### Describe the solution you'd like
Maybe the ability to use a mask like "[AAAA ]*"

**Comment by taflanidi** [comment]
Hey @AlexisQapa, thanks for your suggestion.
My idea is to add a **Pattern Builder** entity, allowing things like

```swift
let formats: [String] = 
    Pattern("[AAAA]")
        .affineRepeat(min: 3, max: 6, separator: " ")
        .suffix("[000]")
        .build

// produces:

[
    "[AAAA] [AAAA] [AAAA]",
    "[AAAA] [AAAA] [AAAA] [AAAA]",
    "[AAAA] [AAAA] [AAAA] [AAAA] [AAAA]",
    "[AAAA] [AAAA] [AAAA] [AAAA] [AAAA] [AAAA]",
    "[AAAA] [AAAA] [AAAA] [AAAA] [AAAA] [AAAA] [000]",
]
```

**Benefits:**

First of all, [affine formats](https://github.com/RedMadRobot/input-mask-ios/wiki/2.1-Affine-Masks) allow us to have a consistent [`complete`](https://github.com/RedMadRobot/input-mask-ios/wiki/2.-Text-Field-Listener#receiving-events) flag value.

```
Output                 Complete

1234 1234 123          False
1234 1234 1234         True
1234 1234 1234 1       False
1234 1234 1234 12      False
1234 1234 1234 123     False
1234 1234 1234 1234    True
```

Second, this **Pattern Builder** approach doesn't require the library to go _full regular expressions syntax_, which is good because I hate the idea.

The only thing is to figure out a usable and practical **Pattern Builder** interface.  
Methods like `affineRepeat(…)` or `suffix(…)` are just a shot in the dark, I made them up and I can't imagine any new ones at the moment, so tell me your thoughts.

**Comment by AlexisQapa** [comment]
Generating all the patterns was my first idea but I didn't knew how to integrate it into the lib. Your builder is definitely a nice solution ! I like how it's just a helper which ppl can opt in opt out

**Comment by taflanidi** [comment]
@AlexisQapa, okay, so let's compose a preliminary interface for this utility.  
Once again, I've got no idea what I'm doing, but let's give it a try.

```swift
class AffinePattern {
  init(format: String)

  /// Make a [AAAaaa] group
  /// 
  /// - parameter count: number of mandatory letters;
  /// - parameter optionalCount: number of optional letters;
  /// 
  /// - returns: An `AffinePattern` instance.
  class func makeLetters(count: Int, optionalCount: Int = 0) -> AffinePattern

  /// Make a [000999] group
  /// 
  /// - parameter count: number of mandatory digits;
  /// - parameter optionalCount: number of optional digits;
  /// 
  /// - returns: An `AffinePattern` instance.
  class func makeDigits(count: Int, optionalCount: Int = 0) -> AffinePattern

  /// Make a repetitive group.
  /// 
  /// - parameter times: number of repetitions; e.g. [3...5]
  /// - parameter separator: a string to be inserted in between repeated groups;
  /// 
  /// - returns: An `AffinePattern` instance.
  /// 
  /// - usage:
  ///   AffinePattern("[00]").repeat(times: [2..4], separator: " ") // is equal to:
  ///   [
  ///     "[00] [00]",
  ///     "[00] [00] [00]",
  ///     "[00] [00] [00] [00]",
  ///   ]
  func repeat(times: Range<Int>, separator: String = "") -> AffinePattern

  /// For each item in a repetitive group append a suffix.
  /// 
  /// - parameter suffix: a string to be appended
  /// 
  /// - returns: An `AffinePattern` instance.
  /// 
  /// - usage:
  ///   AffinePattern("[00]").repeat(times: [2..4], separator: " ").appending(suffix: "[0]") // is equal to:
  ///   [
  ///     "[00] [00] [0]",
  ///     "[00] [00] [00] [0]",
  ///     "[00] [00] [00] [00] [0]",
  ///   ]
  func appending(suffix: String) -> AffinePattern

  /// For each item in a repetitive group insert a prefix.
  /// 
  /// - parameter prefix: a string to be inserted
  /// 
  /// - returns: An `AffinePattern` instance.
  /// 
  /// - usage:
  ///   AffinePattern("[00]").repeat(times: [2..4], separator: " ").inserting(prefix: "[0]") // is equal to:
  ///   [
  ///     "[0] [00] [00]",
  ///     "[0] [00] [00] [00]",
  ///     "[0] [00] [00] [00] [00]",
  ///   ]
  func inserting(prefix: String) -> AffinePattern

  /// Build a repetitive group
  var build: [String]
}
```

Anything missing?

**Comment by AlexisQapa** [comment]
Seems good to me, I think It would be sufficient for my use case.

I've read that Swift 5 is coming with native support for string regex for your information, might be useful at some point.

**Comment by taflanidi** [comment]
Okay, I'll be adding this new utility in the next library update.

> I've read that Swift 5 is coming with native support for string regex for your information, might be useful at some point.

[NSRegularExpression](https://developer.apple.com/documentation/foundation/nsregularexpression).  
Not applicable to our library needs, though.

**Comment by taflanidi** [comment]
Hey @AlexisQapa 
I wonder if this thing is still needed. Could you please give me a hint?

With the introduction of full-fledged number formatting it seems like this thing might be redundant.
