### ISSUE TITLE
Empty mask

### ISSUE THREAD

**Issue by KompoD** [RedMadRobot/input-mask-ios#68]
Hey guys!
I use this mask "[…]", but it doesn't allow me to enter different other symbols like this **, : ; () " \ -**
Can I disable mask or use all symbols, digits, letters, whitespaces?

**Comment by KompoD** [comment]
**Solution:**
```
listener.customNotations = [
            Notation(
                character: "N",
                characterSet: CharacterSet.symbols.union(CharacterSet.whitespaces).union(CharacterSet.decimalDigits).union(CharacterSet.letters).union(CharacterSet.punctuationCharacters),
                isOptional: false
            ),
        ]
listener.primaryMaskFormat = "[N…]"
```

**Comment by taflanidi** [comment]
Hey @KompoD,
Thanks for sharing your solution!

Since you've united pretty much all the character sets, why won't you just use a text field _without_ masking? :D

**Comment by KompoD** [comment]
@taflanidi,
oh man, it's a very long story :D

Thanks for ur library!
