### ISSUE TITLE
Autocomplete on Number Pad keyboard not working.

### ISSUE THREAD

**Issue by nathan-fiscaletti** [RedMadRobot/input-mask-ios#70]
### Prerequisites

* [X] Put an `X` between the brackets on this line if you have done all of the following:
  * read our [Wiki](https://github.com/RedMadRobot/input-mask-ios/wiki);
  * read the entire [Known issues](https://github.com/RedMadRobot/input-mask-ios#knownissues) section;
  * checked that my issue isn't already [filled](https://github.com/RedMadRobot/input-mask-ios/issues?q=is%3Aissue);
  * searched StackOverflow's [`input-mask`](https://stackoverflow.com/questions/tagged/input-mask) tag for similar problems.

### Describe the bug
When using the mask and an autocomplete comes up on the top of the keyboard (for example, the device phone number when using a Number Pad keyboard type), if you tap on that it will not insert it properly. Even if it's in the exact same format as is defined. 

### Steps to reproduce the behaviour:

1. Use this format: `([000]) [000]-[0000]`
2. Use the Number Pad keyboard type with Telephone Number content type.
3. When it displays the auto complete phone number, if you tap it, all that ends up in the textfield is `(`.

**Expected behaviour**
The full phone number to be inserted.

**Actual behaviour**
It's not.

**Platform information**
 - OS version: iOS 11
 - Library version: `'~> 4.1.0'
 - Language: Swift 4.2
 - Device (if bug is device-specific): iPhone 6S

**Comment by taflanidi** [comment]
#54, #57 duplicate.
