### ISSUE TITLE
RCTText/RCTSinglelineTextInputView.h not found

### ISSUE THREAD

**Issue by arshidkv12** [RedMadRobot/input-mask-ios#71]
### Archive error 
RCTText/RCTSinglelineTextInputView.h not found 

 
 
 

**Platform information**
 - OS version: [e.g. iOS 9]
 - Library version: [e.g. 4.1]
 - Language: [e.g. Swift 4.2]
 - Device (if bug is device-specific): [e.g. iPhone6]

**Comment by taflanidi** [comment]
You've got to follow the **Bug report** template in order to create a valid ticket.  
Please re-add these missing sections:
**Prerequisites**
**Describe the bug**
**Steps to reproduce**

**Comment by arshidkv12** [comment]
Am using react native library. https://github.com/react-native-community/react-native-text-input-mask/issues/117

**Comment by taflanidi** [comment]
So what?
