### ISSUE TITLE
Make TextInputDelegate implementation open

### ISSUE THREAD

**Issue by AlexisQapa** [RedMadRobot/input-mask-ios#75]
### Prerequisites

* [X] Put an `X` between the brackets on this line if you have done all of the following:
  * read our [Wiki](https://github.com/RedMadRobot/input-mask-ios/wiki);
  * read the entire [Known issues](https://github.com/RedMadRobot/input-mask-ios#knownissues) section;
  * checked that my feature request isn't already [filled](https://github.com/RedMadRobot/input-mask-ios/issues);
  * searched StackOverflow's [`input-mask`](https://stackoverflow.com/questions/tagged/input-mask) tag for similar problems.

### Summary
Using `MaskedTextInputListener` on iOS 11, I can't override `shouldChangeCharactersIn` as I did for `MaskedTextFieldsDelegate` before. This method is marked public but not open. 

### Motivation
In the known issues in the README you recommend overriding `shouldChangeCharactersIn` but this is not possible with `MaskedTextInputListener`.

### Describe the solution you'd like
Despite I use only `shouldChangeCharactersIn`, mark both methods for textfields and textviews open so in case anyone needs it.

### Describe alternatives you've considered
For now I'm sticking with MaskedTextFieldsDelegate

**Comment by taflanidi** [comment]
Hey @AlexisQapa,

For a quick check, have you tried overriding this one? 

```swift
open func textInput(
    _ textInput: UITextInput,
    isChangingCharactersIn range: NSRange,
    replacementString string: String
) -> Mask.Result
```

`textField (_:shouldChangeCharactersIn:replacementString:)` and `textView(_: shouldChangeTextIn:replacementString:)` had been made non-open on purpose, you shouldn't really alter them.

**Comment by AlexisQapa** [comment]
Thanks, I should have looked harder.
