### ISSUE TITLE
iOS error with input mask.js

### ISSUE THREAD

**Issue by pgennoni** [RedMadRobot/input-mask-ios#77]
hi! i am developing a nativescript app and i am using the input mask plugin.
in android it works! But in ios i get this error
Class "InputMaskDelegateImpl" already implements the "UITextFieldDelegate" protocol.

**Comment by taflanidi** [comment]
First of all, we've got a bug report template — and it is required for you to follow.
Second, we've got no `mask.js` or `InputMaskDelegateImpl` entities in our library.
