### ISSUE TITLE
Improve decimal part formatting

### ISSUE THREAD

**Issue by taflanidi** [RedMadRobot/input-mask-ios#78]
### Prerequisites

* [x] Put an `X` between the brackets on this line if you have done all of the following:
  * read our [Wiki](https://github.com/RedMadRobot/input-mask-ios/wiki);
  * read the entire [Known issues](https://github.com/RedMadRobot/input-mask-ios#knownissues) section;
  * checked that my feature request isn't already [filled](https://github.com/RedMadRobot/input-mask-ios/issues);
  * searched StackOverflow's [`input-mask`](https://stackoverflow.com/questions/tagged/input-mask) tag for similar problems.

### Summary
Make sure right-to-left masks work fine with optional decimals.

Also, add a Wiki page with a tutorial for this feature.

**Comment by kilyan-s** [comment]
Hi, 
I've just started to use this library and I have an issue with digit grouping when right to left is ON.

In the textfield the user has to put the value of an odometer. The mask I'm using is ```[099],[999]``` (I need at least 1 digit and up to 6 digits separated by a comma). Right to left is On and I have a keyboard type: Numbers and Ponctuation for this UITextfield.

This is what I see in the textfield: 
```
Input    -> Result
1        -> 1
12       -> 12
123      -> 123
1234     -> 1,234
12345    -> 12,345
123456   -> 123,456
1234567  -> 234,567
12345678 -> 345,678
```

When Right to left is ON I can type as many digits as I want but it removes the digits at the beginning. If I disable right to left I can't type more than 6 digits.

Is there a way to limit the number of digits when right to left is on ?

System:
```
Xcode version 11.3.1
Simulator iPhone 11 Pro Max, iOS 13.3
Input-mask-ios version 6.0.0 (Installed using CocoaPods)
```

Thanks for your help !

**Comment by taflanidi** [comment]
Hey @kilyan-s,
Thanks for your question.

I know it's a bit frustrating, but that's an expected behaviour you are describing.

There was a [short discussion](https://github.com/RedMadRobot/input-mask-android/issues/95) regarding the Android counterpart of our library with almost the same symptoms.

RTL masks weren't actually intended as a solution for digit grouping. This «feature» is just more of a side effect, and I'm still working on a proper digit grouping with predictable decimal formatting.

**Comment by kilyan-s** [comment]
Hi !
Oh ok got it, thanks for your answer.

**Comment by taflanidi** [comment]
Done.
