### ISSUE TITLE
iOS 13 / XCode 11 Text Input Errors - Swipe Keyboard

### ISSUE THREAD

**Issue by NuVeS** [RedMadRobot/input-mask-ios#81]
### Prerequisites

* [ ] Put an `X` between the brackets on this line if you have done all of the following:
  * read our [Wiki](https://github.com/RedMadRobot/input-mask-ios/wiki);
  * read the entire [Known issues](https://github.com/RedMadRobot/input-mask-ios#knownissues) section;
  * checked that my issue isn't already [filled](https://github.com/RedMadRobot/input-mask-ios/issues?q=is%3Aissue);
  * searched StackOverflow's [`input-mask`](https://stackoverflow.com/questions/tagged/input-mask) tag for similar problems.

### Describe the bug
Using the new swipe keyboard causes the application to freeze and crash.

### Steps to reproduce the behaviour:

1. Start typing
2. Start swipe keyboard on iOS 13

**Expected behaviour**
Work properly, e.g. make an input

**Actual behaviour**
Freeze and crash 

**Screenshots**

**Platform information**
 - OS version: iOS 13
 - Language: Swift 4.2

**Comment by taflanidi** [comment]
Hey @NuVeS,
Thanks for your report.

Please go ahead and try the `MaskedTextInputListener` class. It has the same capabilities, but it uses newer APIs (unified for both `UITextField` and `UITextView`), and thus this utility doesn't have issues with recursive calls. Let me know if it works for you.

Looks like it's finally time to drop the `MaskedTextFieldDelegate` and `MaskedTextViewDelegate` support for good.

P.s. Next time you file an issue, please make sure you've checked the **prerequisites**.

**Comment by taflanidi** [comment]
Closing this and #82 due to inactivity.
