### ISSUE TITLE
Terminating app due to "Range or index out of bounds" exception

### ISSUE THREAD

**Issue by CFIFok** [RedMadRobot/input-mask-ios#84]
### Prerequisites

* [x] Put an `X` between the brackets on this line if you have done all of the following:
  * read our [Wiki](https://github.com/RedMadRobot/input-mask-ios/wiki);
  * read the entire [Known issues](https://github.com/RedMadRobot/input-mask-ios#knownissues) section;
  * checked that my issue isn't already [filled](https://github.com/RedMadRobot/input-mask-ios/issues?q=is%3Aissue);
  * searched StackOverflow's [`input-mask`](https://stackoverflow.com/questions/tagged/input-mask) tag for similar problems.

### Describe the bug
*** Terminating app due to uncaught exception `'NSInvalidArgumentException', reason: '-[__NSCFString replaceCharactersInRange:withString:]:` Range or index out of bounds' in `MaskedTextFieldDelegate.swift` class.

### Steps to reproduce the behaviour:

1. Create an instance of `UITextField` with default properties, listener (`MaskedTextFieldDelegateListener`) and delegate (`MaskedTextFieldDelegate`)
1.1. The delegate should be an instance with `primaryFormat: "[000000]"`(for example `[000000]`, but it can be either `[00]` or `[000]` etc.). The main point is that it should have some kind of symbols limitation.
2. Copy more than 6 symbols in clipboard (depend on the number of zeros in the format `[000000]`).
3. Run the application and navigate to the our `UITextField`.
5. Perform _*three-finger gesture_ on the `UITextField` and tap `Paste` button (_Screenshot 1_) twice. The size limit should be exceeded, but everything will be ok.
6. And finally press the `Undo` button (_Screenshot 1_).
7. Crash!

I have made some analysis of this issue and draw conclusions which are depicted on _Screenshot 2_. Thank you for your cooperation in advance.

**Expected behaviour**
The delegate should perform the undo operation, if possible, otherwise make nothing.

**Actual behaviour**
Terminating app due to "Range or index out of bounds" exception.

**Screenshots**
Screenshot 1
![IMG_001](https://user-images.githubusercontent.com/52627825/79577242-10661d00-80cd-11ea-8901-35143805475c.png)
Screenshot 2
![IMG_002](https://user-images.githubusercontent.com/52627825/79577808-02fd6280-80ce-11ea-803f-330aef5431d1.png)

**Platform information**
 - OS version: iOS 13.0+
 - Library version: 6.0
 - Language: Swift 5.0
 - Device (if bug is device-specific): iPhone7\8\X

**Additional context**
 _*iOS provides built-in gestures for undo, redo, copy, and paste in text views, triggered using a variety of three-finger moves – swiping left and right, or pinching in or out respectively:_ https://www.apple.com/ios/ios-13/features/

**Comment by taflanidi** [comment]
Hey @CFIFok!
Thanks a lot for you heaven-of-a-detailed cool report, things like this massively assist with debugging.

Speaking of which, we'll have an update this week with a few tweaks, and I'd like to include the fix for this bug as well.

**Comment by alkincakiralar1996** [comment]
Any updates ?

**Comment by taflanidi** [comment]
Update is coming in `7.2.0` :D 

That's a marvelous catch, thank you so much!

**Comment by taflanidi** [comment]
@CFIFok mind if I add you to our contributors?

**Comment by taflanidi** [comment]
Meet `7.2.0`.

**Comment by alexander-kurilovich-gismart** [comment]
@taflanidi yep sure! Thanx a lot too 👍
