### ISSUE TITLE
Install in macOS project

### ISSUE THREAD

**Issue by DmitriyTerekhin** [RedMadRobot/input-mask-ios#85]
Hi! It's a good library for iOS. But i wanted to put it in my macOS projects(and i quite new for it). I was trying to install by Cocoapods, but i cant. Then decided to put it by carthage. And i have some problem with it. I cant adding framework to project. Looks like you don't have macOS support?! Or if i wrong could give me some help?

**Comment by taflanidi** [comment]
Hey @DmitriyTerekhin!
Thanks a lot for your question.

Unfortunately, our library lost macOS support eons ago.
We do still have this feature in our [roadmap](https://github.com/RedMadRobot/input-mask-ios/projects), though. You've got to be aware it won't be released anytime soon, but in the meantime you may still `git clone` our repo and link all the important stuff directly into your project. 

Like, for instance, the `Mask` class with all of the underlying logic is platform-agnostic, thus you'll be able to incorporate it given you've built your own macos-textfield-listener on top of it.

**Comment by taflanidi** [comment]
macOS support is a WIP milestone, please keep your eye on the library updates.
