### ISSUE TITLE
Multiple Swift compiler Errors: * is only available in tvOS 10.0 or newer

### ISSUE THREAD

**Issue by Adobels** [RedMadRobot/input-mask-ios#88]
Swift compiler shows multiple `* is only available in tvOS 10.0 or newer` errors when building an app which depends on your framework version 6.0.0 integrated via SPM Xcode 12.2 beta 4 12B5044c

**Comment by smamczak** [comment]
Hi, try removing dependency from the project, clear derived data folder with repository checkout and add the library to your project. It worked for me. This is probably the SPM problem, because after downloading the github repo it compiles fine.

**Comment by taflanidi** [comment]
I've cleaned up the configs a bit, shouldn't be a problem anymore.

Thank you!
