### ISSUE TITLE
How to define ${dynamic amount }/month in input mask

### ISSUE THREAD

**Issue by Joshig99** [RedMadRobot/input-mask-ios#93]
the amount should be dynamic it may be 1 or 10 or 100 or 1000 ...etc,
i defined it like "$[0000]/month"....but it not works for me it showing "/month" after entering 4 digits and also it did not taking more than 4 digits

**Comment by taflanidi** [comment]
Hey @Joshig99 
Thanks for your question. You should probably try our RTL masks for your example, see https://github.com/RedMadRobot/input-mask-ios/wiki/2.2-Right-to-Left-&-Digit-Grouping

Should you have additional questions, please do not hesitate to reopen this issue.
