### ISSUE TITLE
How to write uppercased text?

### ISSUE THREAD

**Issue by DmytroYashchenko** [RedMadRobot/input-mask-ios#95]
I need my textfield to support mask and get only uppercased text in result. As I set my textField delegate as MaskedTextFieldDelegate, I cant use shouldChangeCharactersInRange method, where I get uppercased string  in my code. I can't use autocapitalizationType of the textField because it only affects on keyboard caps. So, any help to get uppercased string from MaskedTextFieldDelegate?

**Comment by taflanidi** [comment]
Hey @DmytroYashchenko 
Thanks for your question.

Subclass the `MaskedTextFieldDelegate`, override the `textField:shouldChangeCharactersIn:replacementString` and put your logic inside, super call is mandatory.

E.g.:

```swift
class MyMaskedTextFieldDelegate: MaskedTextFieldDelegate {
    override func textField(
        _ textField: UITextField,
        shouldChangeCharactersIn range: NSRange,
        replacementString string: String
    ) -> Bool {
        return super.textField(
            textField,
            shouldChangeCharactersIn: range,
            replacementString: string.uppercased()
        )
    }
}
```

**Comment by DmytroYashchenko** [comment]
@taflanidi 
Great solution! It works! Thank you!
