### ISSUE TITLE
Poor performance when user types fast

### ISSUE THREAD

**Issue by kirillzyusko** [RedMadRobot/input-mask-ios#97]
### Prerequisites

* [x] Put an `X` between the brackets on this line if you have done all of the following:
  * read our [Wiki](https://github.com/RedMadRobot/input-mask-ios/wiki);
  * read the entire [Known issues](https://github.com/RedMadRobot/input-mask-ios#knownissues) section;
  * checked that my issue isn't already [filled](https://github.com/RedMadRobot/input-mask-ios/issues?q=is%3Aissue);
  * searched StackOverflow's [`input-mask`](https://stackoverflow.com/questions/tagged/input-mask) tag for similar problems.

### Describe the bug

Hi @taflanidi First of all I wanted to say thank you for the great lib!

However, I found, that if I type really fast, then the input is handled slower, than I typing.

### Steps to reproduce the behaviour:

1. Clone the project
2. Change `value` in `userDefinedRuntimeAttribute` to `[A…]` in sample app
3. Run sample app
4. try to type any random symbols but do it really fast 🙂 

**Expected behaviour**

User should type as fast as he can and no lags/delays should occur (as when using a normal `UITextField`)

**Actual behaviour**

In the beginning I can type in real time mode. However after given time (when I typed quite a lot of characters) the process becomes slower and slower and at some point you can stop typing, but you will see, how new characters still appears.

**Screenshots**

https://user-images.githubusercontent.com/22820318/158359490-3edf5610-5852-4b29-baa8-941412a05843.mov

After the sixth second I don't type anymore, but the characters continue to appear. UI thread FPS goes to 0.

**Platform information**
 - OS version: 15.2
 - Library version: 6.1.0
 - Language: Swift 5
 - Device (if bug is device-specific): I think it's not device-specific, because the issues was reproducible on iPhone 7 (real device) too.

**Additional context**

I didn't dig into the implementation, so I can not say, where the performance drop occurs 😔

**Comment by taflanidi** [comment]
Heya, 
Thanks a lot for your report, gonna look into this.

**Comment by taflanidi** [comment]
Okay, performance hiccup got its cure.

Gonna issue a new version `7.1.1` soon.

**Comment by taflanidi** [comment]
https://github.com/RedMadRobot/input-mask-ios/pull/105
