### ISSUE TITLE
can you make mask template always visible while user input text

### ISSUE THREAD

**Issue by margulan97** [RedMadRobot/input-mask-ios#98]
### Prerequisites

* [x] Put an `X` between the brackets on this line if you have done all of the following:
  * read our [Wiki](https://github.com/RedMadRobot/input-mask-ios/wiki);
  * read the entire [Known issues](https://github.com/RedMadRobot/input-mask-ios#knownissues) section;
  * checked that my feature request isn't already [filled](https://github.com/RedMadRobot/input-mask-ios/issues);
  * searched StackOverflow's [`input-mask`](https://stackoverflow.com/questions/tagged/input-mask) tag for similar problems.

### Summary
I need to make maskExpression template always stay visible while user input text

### Describe alternatives you've considered
<img width="864" alt="Снимок экрана 2023-02-27 в 01 50 43" src="https://user-images.githubusercontent.com/46007319/221433561-bea77bca-1697-4c89-9917-a94b8d5e66fc.png">

I try to make symbols that not in square brackets visible. the result will return in shouldchangecharactersin and I have a problem that cursor going forward and backward while user typing. I have other solution adding label above mask but it's bad. can u help me I'm stuck.

**Comment by taflanidi** [comment]
Done. Please look through the Sample project.
